import '../models/food_item.dart';

// Sample food items data
final FOOD_ITEMS = [
  FoodItem(
    id: '1',
    name: 'Tavuk + Pilav',
    category: 'Yemek',
    price: 200,
    imageUrl: '',
    subCategory: 'Yemek',
  ),
  FoodItem(
    id: '2',
    name: 'Tavuk + Makarna',
    category: 'Yemek',
    price: 180,
    imageUrl: '',
    subCategory: 'Yemek',
  ),
  FoodItem(
    id: '3',
    name: 'Adana Kebap + Pilav',
    category: 'Yemek',
    price: 350,
    imageUrl: '',
    subCategory: 'Yemek',
  ),
  FoodItem(
    id: '4',
    name: 'Lahmacun',
    category: 'Yemek',
    price: 80,
    imageUrl: '',
    subCategory: 'Yemek',
  ),
  FoodItem(
    id: '5',
    name: 'Citir Tavuk',
    category: 'Yemek',
    price: 150,
    imageUrl: '',
    subCategory: 'Yemek',
  ),
  FoodItem(
    id: '6',
    name: 'Patlican Kebabi',
    category: 'Yemek',
    price: 400,
    imageUrl: '',
    subCategory: 'Yemek',
  ),
  FoodItem(
    id: '7',
    name: 'Ayran',
    category: 'Icecek',
    price: 20,
    imageUrl: '',
    subCategory: 'Icecek',
  ),
  FoodItem(
    id: '8',
    name: 'Kola',
    category: 'Icecek',
    price: 40,
    imageUrl: '',
    subCategory: 'Icecek',
  ),
  FoodItem(
    id: '9',
    name: 'Patates Kizartmasi',
    category: 'Atistirmalik',
    price: 70,
    imageUrl: '',
    subCategory: 'Atistirmalik',
  ),
  FoodItem(
    id: '10',
    name: 'Nugget',
    category: 'Atistirmalik',
    price: 70,
    imageUrl: '',
    subCategory: 'Atistirmalik',
  ),
];
