import '../models/food_item.dart';

// Sample food items data
final foodItems = [
  FoodItem(
    id: '1',
    name: 'Tavuk + Pilav',
    category: 'Yemek',
    price: 200,
    imageUrl: 'assets/tavukpilav.png',
    subCategory: 'Yemek',
  ),
  FoodItem(
    id: '2',
    name: 'Tavuk + Makarna',
    category: 'Yemek',
    price: 180,
    imageUrl: 'assets/tavukmakarna.png',
    subCategory: 'Yemek',
  ),
  FoodItem(
    id: '3',
    name: 'Adana Kebap + Pilav',
    category: 'Yemek',
    price: 350,
    imageUrl: 'assets/kebap.png',
    subCategory: 'Yemek',
  ),
  FoodItem(
    id: '4',
    name: 'Lahmacun',
    category: 'Yemek',
    price: 80,
    imageUrl: 'assets/lahmacun.png',
    subCategory: 'Yemek',
  ),
  FoodItem(
    id: '5',
    name: 'Çıtır Tavuk',
    category: 'Atıştırmalık',
    price: 150,
    imageUrl: 'assets/citirtavuk.png',
    subCategory: 'Atıştırmalık',
  ),
  FoodItem(
    id: '6',
    name: 'Patlıcan Kebabı',
    category: 'Yemek',
    price: 400,
    imageUrl: 'assets/patlicankebap.png',
    subCategory: 'Yemek',
  ),
  FoodItem(
    id: '7',
    name: 'Ayran',
    category: 'İçecek',
    price: 20,
    imageUrl: 'assets/ayran.png',
    subCategory: 'İçecek',
  ),
  FoodItem(
    id: '8',
    name: 'Kola',
    category: 'İçecek',
    price: 40,
    imageUrl: 'assets/kola.png',
    subCategory: 'İçecek',
  ),
  FoodItem(
    id: '9',
    name: 'Patates Kızartması',
    category: 'Atıştırmalık',
    price: 70,
    imageUrl: 'assets/patates.png',
    subCategory: 'Atıştırmalık',
  ),
  FoodItem(
    id: '10',
    name: 'Nugget',
    category: 'Atıştırmalık',
    price: 70,
    imageUrl: 'assets/nugget.png',
    subCategory: 'Atıştırmalık',
  ),
];
